name: van_android_getx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  json_annotation: ^4.9.0
  get_storage: ^2.1.1
  url_launcher: ^6.2.2
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1    # 图标生成插件
  flutter_native_splash: ^2.3.8 # 自定义启动页
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter_icons:
  image_path: "assets/images/icon.png"
  android: "ic_launcher"    # 指定生成的图标名
  ios: true    # iOS是否也生成图标

flutter_native_splash:
  color: "79B4EB"
  image: assets/images/icon.png
  android: true
  android_gravity: center
  ios: true
  android_12:
    image: assets/images/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/



